"""
Step 1: LLM identifies ILS-able stochastic component in a program
"""

import json
import logging
import os
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class ILSComponentSpec:
    name: str
    description: str
    type: str  # "continuous" | "discrete" | "constrained"
    ils_type: str  # "A" | "B" | "C" | "unknown"
    language: str  # "python" | "cpp"
    location: str
    degrees_of_freedom: str
    reasoning: str


def _detect_language(code: str) -> str:
    """Detect programming language from code content heuristics."""
    cpp_signals = ["#include", "int main(", "::", "std::", "cout", "scanf", "printf"]
    if any(sig in code for sig in cpp_signals):
        return "cpp"
    return "python"


_SYSTEM_PROMPT = """\
You are an expert algorithm analyst specializing in Iterated Local Search (ILS) and \
combinatorial/numerical optimization. Your task is to analyze a program and identify \
whether it has an ILS-able component — a degree of freedom that, if varied, could \
plausibly produce a better solution than the current one.

IMPORTANT: Be aggressive in identifying ILS-able components. A false positive (running \
ILS on something that turns out not to matter much) costs only compute time. A false \
negative (missing a real ILS opportunity) means leaving a better solution on the table. \
When in doubt, classify as ILS-able.

You must respond with valid JSON only, no markdown code blocks."""

_USER_PROMPT_TEMPLATE = """\
Analyze the following program and identify its ILS-able component.

PROBLEM DESCRIPTION:
{problem_description}

PROGRAM CODE ({language}):
```{language}
{code}
```

=== ILS-ABLE COMPONENT TYPES ===

TYPE A — Stochastic Initialization
  DEFINITION: The program has an explicit random number generator (RNG). The same \
algorithm, run from different random starting configurations, finds different local \
optima. The underlying search space is the space of possible initializations.

  NECESSARY CONDITIONS (all must hold):
    1. Explicit RNG present: np.random, random.seed, mt19937, std::shuffle, etc.
    2. An optimization or local search loop runs after the random initialization.
    3. Different seeds plausibly produce different final solutions (not just different \
intermediate steps that converge to the same answer).

  THE ILS-ABLE COMPONENT IS: The initialization configuration (positions, orderings, \
assignments). The random seed is just the handle used to generate it.

  EXAMPLES:
    • Circle packing: mt19937 rng(time()); for each circle, pick random (x, y) position \
before running gradient descent. ILS-able component = initial circle positions.
    • Stochastic local search: np.random.shuffle(candidates) before greedy improvement. \
ILS-able = candidate ordering generated by shuffle.
    • Simulated annealing: random initial solution before temperature schedule.

  SIGNALS TO LOOK FOR:
    • chrono::steady_clock in seed (time-based = different every run)
    • np.random.seed() or random.seed() before solving
    • shuffle() / sample() / random_permutation() before any optimization loop
    • "random initialization", "random restart" in comments

---

TYPE B — Tunable Continuous Parameters
  DEFINITION: The program is deterministic (or has RNG but the main ILS opportunity is \
not the seed). It contains hardcoded numerical constants that control HOW the algorithm \
behaves. The optimal values of these constants are unknown and likely instance-dependent.

  NECESSARY CONDITIONS (all must hold):
    1. At least one hardcoded numerical constant appears in a formula, comparison, or \
threshold that controls algorithm logic.
    2. Changing the constant changes which decisions the algorithm makes — not just \
how fast it runs (loop bounds) or memory usage (buffer sizes).
    3. A domain expert would deliberately choose a different value of this constant for \
a different problem instance.
    4. The constant encodes a design choice, not an implementation detail.

  THE ILS-ABLE COMPONENT IS: The parameter values themselves. The search space is a \
continuous region around the current values.

  EXAMPLES:
    • Knapsack: sort criterion is v / (mass + volume). The implicit 1:1 weighting \
of mass vs volume is a design choice. If MAX_MASS ≠ MAX_VOLUME, different weights \
may be better. ILS-able = the weighting coefficients (alpha, beta).
    • Kalman filter: process_variance=0.01, measurement_variance=0.1. These are \
calibration constants the algorithm is sensitive to. ILS-able = both variances.
    • Skyline packing: tries W values from sqrt(cells * 0.9) to sqrt(cells * 1.4). \
The multipliers 0.9 and 1.4 bound the search. ILS-able = the range multipliers.
    • Signal processing: window_size=20, overlap=0.5, threshold=0.3.

  NOT Type B (do not flag these):
    • Loop iteration counts like for i in range(100) — changes runtime, not solution
    • Buffer sizes, array capacities — implementation details
    • Print format strings, file paths, debug flags

  REASONING REQUIREMENT: For each parameter you identify, explain WHY changing it \
would plausibly change the output quality, ideally by connecting it to the problem \
structure (e.g. constraint asymmetry, data distribution, algorithm sensitivity).

---

TYPE C — Discrete Combinatorial
  DEFINITION: The program is deterministic. Its output quality is critically sensitive \
to the ORDER or SELECTION of discrete elements processed by a greedy or sequential \
algorithm. Once an element is processed, its placement is fixed — so early decisions \
constrain all future decisions.

  NECESSARY CONDITIONS (all must hold):
    1. A greedy or sequential algorithm processes elements one at a time.
    2. The order in which elements are processed is determined by a sort criterion, \
arbitrary input order, or ID order.
    3. Swapping two elements in the ordering would change the downstream decisions \
made for both elements.
    4. The combinatorial space (n! orderings of n elements) is large enough that the \
chosen ordering is unlikely to be globally optimal.

  THE ILS-ABLE COMPONENT IS: The ordering or selection of elements. The search space \
is the set of all permutations (or subsets).

  EXAMPLES:
    • Polyomino packing: pieces are sorted by size, then placed one by one with greedy \
skyline. A different sort order → different anchor piece → different layout. ILS-able \
= the piece placement ordering.
    • Bin packing: items sorted by decreasing size. Different ordering → different bins \
used. ILS-able = item ordering.
    • Graph coloring with greedy vertex ordering: order in which vertices are colored \
determines how many colors are needed. ILS-able = vertex ordering.
    • Scheduling: jobs sorted by deadline, processed greedily. ILS-able = job sequence.

  DISTINCTION FROM Type B: Type B tunes a continuous scalar that controls logic. \
Type C rearranges discrete elements fed into fixed logic. Changing the sort key \
coefficient from 1.0 to 1.5 is Type B. Changing which element is placed first is Type C.

---

TYPE unknown — No Clear ILS-able Component
  Use this ONLY when:
    • The program is interactive (score measures query count against an adaptive judge — \
      the algorithm's complexity class dominates, not initialization).
    • The program is purely deterministic with no configurable parameters AND no \
      ordering sensitivity (e.g. closed-form formula, exact algorithm with no heuristics).
    • The program is too complex to reliably analyze statically.

  POLICY: Even for Type unknown, set is_ils_able=true and give the LLM discretion to \
propose experiments. Missing a real ILS opportunity is worse than a failed experiment.

  EXCEPTION — set is_ils_able=false ONLY IF:
    • The program is provably an exact algorithm with no heuristic choices (e.g. Dijkstra,
      FFT, exact DP).
    • OR the program is an interactive query-response algorithm where score = query count
      and ALL variants have the same asymptotic query complexity.

=== RESPONSE FORMAT ===

Respond with exactly this JSON (no markdown):

If ILS-able (use for Type A, B, C, and unknown unless exception above applies):
{{
  "is_ils_able": true,
  "ils_type": "<A|B|C|unknown>",
  "component": {{
    "name": "<short name, e.g. 'piece_ordering' or 'density_weights' or 'init_positions'>",
    "description": "<1-2 sentences: what the component is and what it controls>",
    "type": "<continuous|discrete|constrained>",
    "location": "<function name(s) and approximate line numbers or region>",
    "degrees_of_freedom": "<concrete description: e.g. 'ordering of N=1000 pieces', 'alpha in [0.1, 3.0], beta in [0.1, 3.0]', 'x,y coordinates of N circles'>"
  }},
  "reasoning": "<explain: (1) which type (A/B/C/unknown) and why, (2) what specifically can be varied, (3) a concrete argument for WHY varying it would change output quality — connect to problem structure, constraint asymmetry, or algorithm sensitivity>"
}}

If provably not ILS-able (only use the narrow exceptions above):
{{
  "is_ils_able": false,
  "ils_type": null,
  "reasoning": "<specific argument for why NO component fits A/B/C and the program meets the narrow exception criteria>"
}}"""


def analyze_program(
    program,
    problem_description: str = "",
    language: Optional[str] = None,
    llm_model: str = "claude-sonnet-4-6",
    llm_api_key: Optional[str] = None,
) -> Optional[ILSComponentSpec]:
    """
    Use LLM to analyze a program and identify its ILS-able component.

    Args:
        program: Program object with .code attribute
        problem_description: Optional domain context
        language: "python" or "cpp" (auto-detected if not provided)
        llm_model: Anthropic model name
        llm_api_key: API key (defaults to OPENROUTER_API_KEY env var)

    Returns:
        ILSComponentSpec if ILS-able, None otherwise
    """
    from openai import OpenAI

    api_key = llm_api_key or os.environ.get("OPENROUTER_API_KEY")
    client = OpenAI(api_key=api_key, base_url="https://openrouter.ai/api/v1")

    detected_language = language or _detect_language(program.code)

    prompt = _USER_PROMPT_TEMPLATE.format(
        problem_description=problem_description or "No description provided.",
        code=program.code,
        language=detected_language,
    )

    logger.info(
        f"Analyzing program {program.id} for ILS-able components (language={detected_language})..."
    )

    try:
        response = client.chat.completions.create(
            model=llm_model,
            max_tokens=2048,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
        )

        raw = response.choices[0].message.content.strip()

        # Strip markdown code blocks if present
        if raw.startswith("```"):
            lines = raw.split("\n")
            raw = "\n".join(lines[1:-1] if lines[-1] == "```" else lines[1:])

        result = json.loads(raw)

    except json.JSONDecodeError as e:
        logger.warning(f"Failed to parse LLM JSON response: {e}. Marking as not ILS-able.")
        return None
    except Exception as e:
        logger.error(f"LLM call failed during ILS analysis: {e}")
        raise

    if not result.get("is_ils_able", False):
        logger.info(f"Program {program.id} is not ILS-able: {result.get('reasoning', '')}")
        return None

    comp = result.get("component", {})
    ils_type = result.get("ils_type", "unknown") or "unknown"

    spec = ILSComponentSpec(
        name=comp.get("name", "unknown"),
        description=comp.get("description", ""),
        type=comp.get("type", "continuous"),
        ils_type=ils_type,
        language=detected_language,
        location=comp.get("location", ""),
        degrees_of_freedom=comp.get("degrees_of_freedom", ""),
        reasoning=result.get("reasoning", ""),
    )

    logger.info(
        f"Program {program.id} is ILS-able. Type={spec.ils_type}, language={spec.language}, "
        f"component='{spec.name}' at {spec.location}"
    )
    return spec
